# Site settings
title: KenDevDesigns
email: kennethwang14@gmail.com
description: Iâ€™m a product designer based in Sydney. I turn complex ideas into intuitive, beautiful products.
baseurl: ""
url: "http://kendevdesigns.com"
permalink: /:categories/:title


#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge

# The release of Jekyll Now that you're using
version: v1.1.0

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME